-- Roles. Start with a super-user role which has access to everything. Add more roles from the web forms.
insert into role set rolename='su', privilege='2147483623';

-- User. Add an admin user with default password of 'mypassword!'. Change the password after initial login. Has 'su' role.
insert into user set loginid='admin', passwd='zZ0MXYLX07ks8rgt1vW48AFzBq9pWTR0RAYohA==', username='Administrator', status='1', roleid='1';

-- Part groups. Categories to assign parts to. Edit as required.
-- (part group text, location for datasheets)
insert into pgroups set catdescr='Assembly (internal)', datadir='assembly/internal';
insert into pgroups set catdescr='Assembly (external)', datadir='assembly/external';
insert into pgroups set catdescr='Battery', datadir='battery';
insert into pgroups set catdescr='Cable', datadir='cable';
insert into pgroups set catdescr='Capacitor other', datadir='capacitor/other';
insert into pgroups set catdescr='Capacitor SMD ceramic', datadir='capacitor/smd';
insert into pgroups set catdescr='Capacitor SMD tantalum', datadir='capacitor/smd';
insert into pgroups set catdescr='Capacitor SMD electrolytic', datadir='capacitor/smd';
insert into pgroups set catdescr='Capacitor thru-hole ceramic', datadir='capacitor/thruhole';
insert into pgroups set catdescr='Capacitor thru-hole electrolytic', datadir='capacitor/thruhole';
insert into pgroups set catdescr='Capacitor thru-hole poly', datadir='capacitor/thruhole';
insert into pgroups set catdescr='Capacitor thru-hole tantalum', datadir='capacitor/thruhole';
insert into pgroups set catdescr='Capacitor thru-hole trimmer', datadir='capacitor/thruhole';
insert into pgroups set catdescr='Capacitor SMD trimmer', datadir='capacitor/smd';
insert into pgroups set catdescr='Connector audio RCA', datadir='connector/audio';
insert into pgroups set catdescr='Connector audio phone', datadir='connector/audio';
insert into pgroups set catdescr='Connector audio XLR', datadir='connector/audio';
insert into pgroups set catdescr='Connector crimp lug', datadir='connector/crimp';
insert into pgroups set catdescr='Connector D type', datadir='connector/dtype';
insert into pgroups set catdescr='Connector DIN41612', datadir='connector/din41612';
insert into pgroups set catdescr='Connector modular RJ', datadir='connector/modular';
insert into pgroups set catdescr='Connector multipole crimp/PCB', datadir='connector/crimp';
insert into pgroups set catdescr='Connector multipole MIL', datadir='connector/crimp';
insert into pgroups set catdescr='Connector other', datadir='connector/other';
insert into pgroups set catdescr='Connector DC barrel', datadir='connector/power';
insert into pgroups set catdescr='Connector power', datadir='connector/power';
insert into pgroups set catdescr='Connector RF BNC/PL/F', datadir='connector/rf';
insert into pgroups set catdescr='Connector ribbon header', datadir='connector/ribbon';
insert into pgroups set catdescr='Connector terminal block', datadir='connector/tb';
insert into pgroups set catdescr='Crystal SMD', datadir='crystal/smd';
insert into pgroups set catdescr='Crystal thru-hole', datadir='crystal/thruhole';
insert into pgroups set catdescr='Diode bridge other', datadir='diode/bridge';
insert into pgroups set catdescr='Diode bridge thru-hole', datadir='diode/bridge';
insert into pgroups set catdescr='Diode bridge SMD', datadir='diode/bridge';
insert into pgroups set catdescr='Diode rectifier SMD', datadir='diode/rectifier';
insert into pgroups set catdescr='Diode rectifier thru-hole', datadir='diode/rectifier';
insert into pgroups set catdescr='Diode schottky SMD', datadir='diode/schottky';
insert into pgroups set catdescr='Enclosure', datadir='enclosure';
insert into pgroups set catdescr='Fuse', datadir='fuse';
insert into pgroups set catdescr='Fuse mounting SMD', datadir='fuse';
insert into pgroups set catdescr='Fuse mounting thru-hole', datadir='fuse';
insert into pgroups set catdescr='IC interface', datadir='ic/interface';
insert into pgroups set catdescr='IC linear op amp', datadir='ic/linear/opamp';
insert into pgroups set catdescr='IC voltage regulator', datadir='ic/linear/regulator';
insert into pgroups set catdescr='IC linear special function', datadir='ic/linear/special';
insert into pgroups set catdescr='IC logic', datadir='ic/logic';
insert into pgroups set catdescr='IC memory DRAM', datadir='ic/memory/dram';
insert into pgroups set catdescr='IC MPU Coldfire', datadir='ic/mpu/coldfire';
insert into pgroups set catdescr='IC peripheral ethernet', datadir='ic/peripheral/ethernet';
insert into pgroups set catdescr='IC PLD/CPLD', datadir='ic/pld/cpld';
insert into pgroups set catdescr='Inductor ferrite SMD', datadir='inductor/ferrite';
insert into pgroups set catdescr='Inductor power thru-hole', datadir='inductor/power';
insert into pgroups set catdescr='Inductor other', datadir='inductor/other';
insert into pgroups set catdescr='Label', datadir='label';
insert into pgroups set catdescr='LED display other', datadir='display/led';
insert into pgroups set catdescr='LED display SMD', datadir='display/led';
insert into pgroups set catdescr='LED display thru-hole', datadir='display/led';
insert into pgroups set catdescr='LED SMD', datadir='led/smd';
insert into pgroups set catdescr='LED thru-hole', datadir='led/thruhole';
insert into pgroups set catdescr='LED other', datadir='led/other';
insert into pgroups set catdescr='LCD display', datadir='display/lcd';
insert into pgroups set catdescr='Misc', datadir='misc';
insert into pgroups set catdescr='Oscillator SMD', datadir='oscillator';
insert into pgroups set catdescr='Oscillator thru-hole', datadir='oscillator';
insert into pgroups set catdescr='PCB', datadir='pcb';
insert into pgroups set catdescr='Potentiometer', datadir='potentiometer';
insert into pgroups set catdescr='Resistor other', datadir='resistor/other';
insert into pgroups set catdescr='Resistor SMD', datadir='resistor/smd';
insert into pgroups set catdescr='Resistor thru-hole', datadir='resistor/thruhole';
insert into pgroups set catdescr='Transformer other', datadir='transformer/other';
insert into pgroups set catdescr='Transformer audio', datadir='transformer/audio';
insert into pgroups set catdescr='Transformer network', datadir='transformer/network';
insert into pgroups set catdescr='Transistor SMD BJT', datadir='transistor/bjt/smd';
insert into pgroups set catdescr='Transistor thru-hole BJT', datadir='transistor/bjt/thruhole';
insert into pgroups set catdescr='Transistor other BJT', datadir='transistor/bjt/other';
insert into pgroups set catdescr='Transistor SMD FET', datadir='transistor/fet/smd';
insert into pgroups set catdescr='Transistor thru-hole FET', datadir='transistor/fet/thruhole';
insert into pgroups set catdescr='Transistor other FET', datadir='transistor/fet/other';
insert into pgroups set catdescr='Transistor SMD MOSFET', datadir='transistor/fet/smd';
insert into pgroups set catdescr='Transistor thru-hole MOSFET', datadir='transistor/fet/thruhole';
insert into pgroups set catdescr='Transistor other MOSFET', datadir='transistor/fet/other';
insert into pgroups set catdescr='Varistor SMD', datadir='varistor';
insert into pgroups set catdescr='Varistor thru-hole', datadir='varistor';
insert into pgroups set catdescr='Varistor other', datadir='varistor';
insert into pgroups set catdescr='IC peripheral supervisory', datadir='ic/peripheral/supervisory';
insert into pgroups set catdescr='Switch toggle', datadir='switch/toggle';
insert into pgroups set catdescr='Switch pushbutton', datadir='switch/pushbutton';
insert into pgroups set catdescr='Switch rotary', datadir='switch/rotary';
insert into pgroups set catdescr='Switch slide', datadir='switch/slide';
insert into pgroups set catdescr='Switch other', datadir='switch/other';
insert into pgroups set catdescr='Heatsink', datadir='heatsink';
insert into pgroups set catdescr='Resistor network SMD', datadir='resistor/network';
insert into pgroups set catdescr='Resistor network thru-hole', datadir='resistor/network';
insert into pgroups set catdescr='IC MPU PIC', datadir='ic/mpu/pic';
insert into pgroups set catdescr='IC MPU ARM', datadir='ic/mpu/arm';
insert into pgroups set catdescr='IC memory EEPROM', datadir='ic/memory/eeprom';
insert into pgroups set catdescr='IC memory FLASH', datadir='ic/memory/flash';
insert into pgroups set catdescr='IC memory SRAM', datadir='ic/memory/sram';
insert into pgroups set catdescr='IC peripheral serial', datadir='ic/peripheral/serial';
insert into pgroups set catdescr='Inductor ferrite thruhole', datadir='inductor/ferrite';
insert into pgroups set catdescr='Inductor power SMD', datadir='inductor/power';
insert into pgroups set catdescr='Transformer power', datadir='transformer/power';
insert into pgroups set catdescr='Diode small signal thru-hole', datadir='diode/signal';
insert into pgroups set catdescr='Diode small signal SMD', datadir='diode/signal';
insert into pgroups set catdescr='Diode zener thru-hole', datadir='diode/zener';
insert into pgroups set catdescr='Diode zener SMD', datadir='diode/zener';
insert into pgroups set catdescr='IC opto', datadir='ic/opto';
insert into pgroups set catdescr='Diode schottky thru-hole', datadir='diode/schottky';
insert into pgroups set catdescr='Hardware knob 6.4mm grub screw', datadir='hardware/knob';
insert into pgroups set catdescr='Hardware knob metric 18T spline', datadir='hardware/knob';
insert into pgroups set catdescr='Switch rocker', datadir='switch/rocker';
insert into pgroups set catdescr='LDR', datadir='resistor/ldr';
insert into pgroups set catdescr='Relay thruhole', datadir='relay';
insert into pgroups set catdescr='Relay SMD', datadir='relay';
insert into pgroups set catdescr='Relay chassis mount', datadir='relay';
insert into pgroups set catdescr='Connector IC socket', datadir='connector/icsocket';
insert into pgroups set catdescr='Diode network SMD', datadir='diode/network';
insert into pgroups set catdescr='Diode network thru-hole', datadir='diode/network';
insert into pgroups set catdescr='Hardware knob 6.4mm collet', datadir='hardware/knob';
insert into pgroups set catdescr='Connector SIL header', datadir='connector/sil';
insert into pgroups set catdescr='Sensor', datadir='sensor';
insert into pgroups set catdescr='IC memory EPROM', datadir='ic/memory/eprom';
insert into pgroups set catdescr='Triac thru-hole', datadir='triac/thruhole';
 
-- Component Status. Status value for a component. Edit as required.
insert into compstates set statedescr='Not approved';
insert into compstates set statedescr='Approved - production';
insert into compstates set statedescr='Obsolete - pending';
insert into compstates set statedescr='Obsolete';

-- Component Footprints. The PCB footprint type for the component. Edit as requried.
insert into footprint set fprintdescr='DIP-4 300mil';
insert into footprint set fprintdescr='DIP-6 300mil';
insert into footprint set fprintdescr='DIP-8 300mil';
insert into footprint set fprintdescr='DIP-14 300mil';
insert into footprint set fprintdescr='DIP-14 300mil';
insert into footprint set fprintdescr='DIP-16 300mil';
insert into footprint set fprintdescr='DIP-18 300mil';
insert into footprint set fprintdescr='DIP-20 300mil';
insert into footprint set fprintdescr='DIP-24 300mil';
insert into footprint set fprintdescr='DIP-24 400mil';
insert into footprint set fprintdescr='DIP-24 600mil';
insert into footprint set fprintdescr='DIP-22 300mil';
insert into footprint set fprintdescr='DIP-28 300mil';
insert into footprint set fprintdescr='DIP-28 600mil';
insert into footprint set fprintdescr='DIP-32 600mil';
insert into footprint set fprintdescr='DIP-40 600mil';
insert into footprint set fprintdescr='SMD 0805';
insert into footprint set fprintdescr='SMD 0603';
insert into footprint set fprintdescr='SMD 1206';
insert into footprint set fprintdescr='SMD custom';
insert into footprint set fprintdescr='thru-hole custom';


